### PR TITLE
Old version of Apple home page clone

### PR DESCRIPTION
**Pull request by 8Bts**
On the initial commit, I created a basic structure for the page using semantics:

- div class="page-div"  element for as a whole page container.

- nav element for navbar

- section element for middle texts

- main element for 4 pictures above the footer

- footer for the bottom texts and links

Added contents for elements in the order of element declaration.
Used tools specified in the readme for creating a gradient background
Elements are positioned using FlexBox and Float

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @8Bts 👏 👏 
### You did a good job 💪 but there are still some requirements missing in the project implementation. Check my comments 👇 

**_1. The first eight elements of the navbar should be links (to other sections or #) but use span. I'll suggest that you wrap the text in the span with a link tag or change the span tags to link tags._**

**_2. The bottom four elements should be links (to other articles or `#`) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))_**

**_3. Change the project name in your readme to the actual name of your project._**

**_4. Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))_**

**_Try to add float to your CSS style rules_**

### Optional:
**_Try to improve the semantic of the Html structure by moving the section on line 38 - 54 to within the main tag._**

**_if you have any doubts or questions contact me on slack._**

### Reviewed by _Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Comment by 8Bts** [comment]
Thanks for review @lekegitrepo. I fixed all problems that you mentioned.

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :fireworks: :fireworks:  :fireworks: 

Hi @8Bts :smile: 

Congrats on the hard work, you did a great job and your project was approved :1st_place_medal: :1st_place_medal: 

:trophy: You got the main idea of the name of the branches :muscle: Big congrats on that!

:bulb: :bulb: SUGGESTION :bulb: :bulb:
- Can you please update the live version to show hyperlinks? In your readme, there are few links. The way to do it is just as the usual `<a href="">Live version</a>`  


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by 8Bts** [comment]
Thanks for your review and suggestion @thsvr 😄 
I hid all hyperlinks in readme file also 😉 👍

**Pull request merged**
